// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWxDf2YbRpVpnfQr2ABLzf3zaAOe4mqfg',
    appId: '1:683416806905:web:87c62d663db5cc1aad0928',
    messagingSenderId: '683416806905',
    projectId: 'nurture-sync',
    authDomain: 'nurture-sync.firebaseapp.com',
    storageBucket: 'nurture-sync.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXEsqwLd94zzsAF6WJR6s78H21pU06o8M',
    appId: '1:683416806905:android:f24524b18822122fad0928',
    messagingSenderId: '683416806905',
    projectId: 'nurture-sync',
    storageBucket: 'nurture-sync.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDluDB-fJob37uUvhpBRPyLLHuZ8Tlsl1o',
    appId: '1:683416806905:ios:926248e21268ff49ad0928',
    messagingSenderId: '683416806905',
    projectId: 'nurture-sync',
    storageBucket: 'nurture-sync.firebasestorage.app',
    androidClientId: '683416806905-ps6asb8cbo6seufqea4ldkfn0bqpjbn6.apps.googleusercontent.com',
    iosClientId: '683416806905-cef733l94f4ckj3saffnr40492i40rj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.nurtureSync',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDluDB-fJob37uUvhpBRPyLLHuZ8Tlsl1o',
    appId: '1:683416806905:ios:926248e21268ff49ad0928',
    messagingSenderId: '683416806905',
    projectId: 'nurture-sync',
    storageBucket: 'nurture-sync.firebasestorage.app',
    androidClientId: '683416806905-ps6asb8cbo6seufqea4ldkfn0bqpjbn6.apps.googleusercontent.com',
    iosClientId: '683416806905-cef733l94f4ckj3saffnr40492i40rj1.apps.googleusercontent.com',
    iosBundleId: 'com.example.nurtureSync',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWxDf2YbRpVpnfQr2ABLzf3zaAOe4mqfg',
    appId: '1:683416806905:web:87c62d663db5cc1aad0928',
    messagingSenderId: '683416806905',
    projectId: 'nurture-sync',
    authDomain: 'nurture-sync.firebaseapp.com',
    storageBucket: 'nurture-sync.firebasestorage.app',
  );

}